Repository Leafresh-2024/Leafresh-Backend, pull requests merged in 2024-09, with the labels that each got.

#1 feat : login
  build.gradle
  src/main/java/com/leafresh/backend/ReafreshBackendApplication.java
  src/main/java/com/leafresh/backend/ftp/controller/FTPController.java
  src/main/java/com/leafresh/backend/ftp/service/FtpImgLoaderUtil2.java
  src/main/java/com/leafresh/backend/oauth/config/AppProperties.java
  src/main/java/com/leafresh/backend/oauth/config/SecurityConfig.java
  src/main/java/com/leafresh/backend/oauth/config/WebMvcConfig.java
  src/main/java/com/leafresh/backend/oauth/controller/AuthController.java
  src/main/java/com/leafresh/backend/oauth/controller/UserController.java
  src/main/java/com/leafresh/backend/oauth/exception/BadRequestException.java
  src/main/java/com/leafresh/backend/oauth/exception/OAuth2AuthenticationProcessingException.java
  src/main/java/com/leafresh/backend/oauth/exception/ResourceNotFoundException.java
  src/main/java/com/leafresh/backend/oauth/model/AuthProvider.java
  src/main/java/com/leafresh/backend/oauth/model/User.java
  src/main/java/com/leafresh/backend/oauth/payload/ApiResponse.java
  src/main/java/com/leafresh/backend/oauth/payload/AuthResponse.java
  src/main/java/com/leafresh/backend/oauth/payload/LoginRequest.java
  src/main/java/com/leafresh/backend/oauth/payload/SignUpRequest.java
  src/main/java/com/leafresh/backend/oauth/repository/UserRepository.java
  src/main/java/com/leafresh/backend/oauth/security/CurrentUser.java
  src/main/java/com/leafresh/backend/oauth/security/CustomUserDetailsService.java
  src/main/java/com/leafresh/backend/oauth/security/RestAuthenticationEntryPoint.java
  src/main/java/com/leafresh/backend/oauth/security/TokenAuthenticationFilter.java
  src/main/java/com/leafresh/backend/oauth/security/TokenProvider.java
  src/main/java/com/leafresh/backend/oauth/security/UserPrincipal.java
  src/main/java/com/leafresh/backend/oauth/security/oauth2/CustomOAuth2UserService.java
  src/main/java/com/leafresh/backend/oauth/security/oauth2/HttpCookieOAuth2AuthorizationRequestRepository.java
  src/main/java/com/leafresh/backend/oauth/security/oauth2/OAuth2AuthenticationFailureHandler.java
  src/main/java/com/leafresh/backend/oauth/security/oauth2/OAuth2AuthenticationSuccessHandler.java
  src/main/java/com/leafresh/backend/oauth/security/oauth2/user/FacebookOAuth2UserInfo.java
  src/main/java/com/leafresh/backend/oauth/security/oauth2/user/GithubEmailInfo.java
  src/main/java/com/leafresh/backend/oauth/security/oauth2/user/GithubOAuth2UserInfo.java
  src/main/java/com/leafresh/backend/oauth/security/oauth2/user/GoogleOAuth2UserInfo.java
  src/main/java/com/leafresh/backend/oauth/security/oauth2/user/KakaoOAuth2UserInfo.java
  src/main/java/com/leafresh/backend/oauth/security/oauth2/user/NaverOAuth2UserInfo.java
  src/main/java/com/leafresh/backend/oauth/security/oauth2/user/OAuth2UserInfo.java
  src/main/java/com/leafresh/backend/oauth/security/oauth2/user/OAuth2UserInfoFactory.java
  src/main/java/com/leafresh/backend/oauth/util/CookieUtils.java
Labels: good first issue

#2 feat : login
  src/main/java/com/leafresh/backend/ftp/controller/FTPController.java
  src/main/java/com/leafresh/backend/oauth/config/SecurityConfig.java
Labels: enhancement

#3 refactor : code modify
  src/main/java/com/leafresh/backend/oauth/config/AppProperties.java
  src/main/java/com/leafresh/backend/oauth/config/SecurityConfig.java
  src/main/java/com/leafresh/backend/oauth/controller/AuthController.java
  src/main/java/com/leafresh/backend/oauth/controller/UserController.java
  src/main/java/com/leafresh/backend/oauth/exception/OAuth2AuthenticationProcessingException.java
  src/main/java/com/leafresh/backend/oauth/model/AuthProvider.java
  src/main/java/com/leafresh/backend/oauth/model/Role.java
  src/main/java/com/leafresh/backend/oauth/model/User.java
  src/main/java/com/leafresh/backend/oauth/model/UserStatus.java
  src/main/java/com/leafresh/backend/oauth/payload/SignUpRequest.java
  src/main/java/com/leafresh/backend/oauth/repository/UserRepository.java
  src/main/java/com/leafresh/backend/oauth/security/CustomUserDetailsService.java
  src/main/java/com/leafresh/backend/oauth/security/TokenAuthenticationFilter.java
  src/main/java/com/leafresh/backend/oauth/security/TokenProvider.java
  src/main/java/com/leafresh/backend/oauth/security/UserPrincipal.java
  src/main/java/com/leafresh/backend/oauth/security/oauth2/CustomOAuth2UserService.java
  src/main/java/com/leafresh/backend/oauth/security/oauth2/HttpCookieOAuth2AuthorizationRequestRepository.java
  src/main/java/com/leafresh/backend/oauth/security/oauth2/OAuth2AuthenticationFailureHandler.java
  src/main/java/com/leafresh/backend/oauth/security/oauth2/OAuth2AuthenticationSuccessHandler.java
  src/main/java/com/leafresh/backend/oauth/security/oauth2/user/FacebookOAuth2UserInfo.java
  src/main/java/com/leafresh/backend/oauth/security/oauth2/user/GithubEmailInfo.java
  src/main/java/com/leafresh/backend/oauth/security/oauth2/user/GithubOAuth2UserInfo.java
  src/main/java/com/leafresh/backend/oauth/security/oauth2/user/GoogleOAuth2UserInfo.java
  src/main/java/com/leafresh/backend/oauth/security/oauth2/user/KakaoOAuth2UserInfo.java
  src/main/java/com/leafresh/backend/oauth/security/oauth2/user/NaverOAuth2UserInfo.java
  src/main/java/com/leafresh/backend/oauth/security/oauth2/user/OAuth2UserInfo.java
  src/main/java/com/leafresh/backend/oauth/security/oauth2/user/OAuth2UserInfoFactory.java
Labels: enhancement

#7 feat : Add feed function
  src/main/java/com/leafresh/backend/feed/controller/FeedController.java
  src/main/java/com/leafresh/backend/feed/model/dto/FeedDTO.java
  src/main/java/com/leafresh/backend/feed/model/entity/FeedEntity.java
  src/main/java/com/leafresh/backend/feed/model/entity/FeedStatus.java
  src/main/java/com/leafresh/backend/feed/repository/FeedRepository.java
  src/main/java/com/leafresh/backend/feed/service/FeedService.java
Labels: Developing

#13 refactor : 로그인 롬복 삭제 및 코드 리팩토리
  src/main/java/com/leafresh/backend/oauth/config/SecurityConfig.java
  src/main/java/com/leafresh/backend/oauth/controller/AuthController.java
  src/main/java/com/leafresh/backend/oauth/model/User.java
  src/main/java/com/leafresh/backend/oauth/payload/ApiResponse.java
  src/main/java/com/leafresh/backend/oauth/payload/AuthResponse.java
  src/main/java/com/leafresh/backend/oauth/payload/LoginRequest.java
  src/main/java/com/leafresh/backend/oauth/payload/SignUpRequest.java
  src/main/java/com/leafresh/backend/oauth/security/TokenAuthenticationFilter.java
  src/main/java/com/leafresh/backend/oauth/service/CustomUserDetailsService.java
  src/main/java/com/leafresh/backend/oauth/service/TokenProvider.java
  src/main/java/com/leafresh/backend/oauth/util/CookieUtils.java
Labels: enhancement

#18 feat: add todo
  src/main/java/com/leafresh/backend/oauth/config/SecurityConfig.java
  src/main/java/com/leafresh/backend/todo/controller/ToDoController.java
  src/main/java/com/leafresh/backend/todo/model/ToDoDTO.java
  src/main/java/com/leafresh/backend/todo/model/ToDoEntity.java
  src/main/java/com/leafresh/backend/todo/repository/TodoRepository.java
  src/main/java/com/leafresh/backend/todo/service/ToDoService.java
  src/main/resources/application.yml
Labels: Developing

#19 Update application.yml
  src/main/resources/application.yml
Labels: Fixed

#33 feat: plantcare calandcheck
  src/main/java/com/leafresh/backend/plantcare/controller/PlantCareController.java
  src/main/java/com/leafresh/backend/plantcare/model/PlantCareDTO.java
  src/main/java/com/leafresh/backend/plantcare/model/PlantCareEntity.java
  src/main/java/com/leafresh/backend/plantcare/repository/PlantCareRepository.java
  src/main/java/com/leafresh/backend/plantcare/service/PlantCareService.java
Labels: Developing

#34 fix : feed fixed
  src/main/java/com/leafresh/backend/feed/controller/FeedController.java
  src/main/java/com/leafresh/backend/feed/model/dto/FeedDTO.java
  src/main/java/com/leafresh/backend/feed/model/entity/FeedEntity.java
  src/main/java/com/leafresh/backend/feed/repository/FeedRepository.java
  src/main/java/com/leafresh/backend/feed/service/FeedService.java
  src/main/resources/application.yml
Labels: Fixed

#37 fix: plantcare calandcheck
  src/main/java/com/leafresh/backend/plantcare/controller/PlantCareController.java
  src/main/java/com/leafresh/backend/plantcare/model/PlantCareEntity.java
Labels: Developing

#39 fix : feed fixed
  src/main/java/com/leafresh/backend/feed/controller/FeedController.java
  src/main/java/com/leafresh/backend/feed/model/dto/FeedDTO.java
  src/main/java/com/leafresh/backend/feed/model/entity/FeedEntity.java
  src/main/java/com/leafresh/backend/feed/repository/FeedRepository.java
  src/main/java/com/leafresh/backend/feed/service/FeedService.java
Labels: Fixed

#40 Leafresh/main diary feed v2
  src/main/java/com/leafresh/backend/feed/model/dto/FeedDTO.java
  src/main/java/com/leafresh/backend/feed/model/entity/FeedEntity.java
  src/main/java/com/leafresh/backend/feed/service/FeedService.java
Labels: Fixed

#44 fix : feed fixed
  src/main/java/com/leafresh/backend/feed/model/dto/FeedDTO.java
  src/main/java/com/leafresh/backend/feed/model/entity/FeedEntity.java
  src/main/java/com/leafresh/backend/feed/service/FeedService.java
Labels: Completion

#45 fix: todo
  src/main/java/com/leafresh/backend/todo/controller/ToDoController.java
  src/main/java/com/leafresh/backend/todo/model/ToDoDTO.java
  src/main/java/com/leafresh/backend/todo/model/ToDoEntity.java
  src/main/java/com/leafresh/backend/todo/repository/TodoRepository.java
  src/main/java/com/leafresh/backend/todo/service/ToDoService.java
Labels: Developing

#49 fix: todo todo
  src/main/java/com/leafresh/backend/todo/controller/ToDoController.java
  src/main/java/com/leafresh/backend/todo/model/ToDoDTO.java
  src/main/java/com/leafresh/backend/todo/repository/TodoRepository.java
  src/main/java/com/leafresh/backend/todo/service/ToDoService.java
Labels: Developing

#52 fix: todo & plantCare
  src/main/java/com/leafresh/backend/plantcare/controller/PlantCareController.java
  src/main/java/com/leafresh/backend/plantcare/model/PlantCareDTO.java
  src/main/java/com/leafresh/backend/plantcare/service/PlantCareService.java
  src/main/java/com/leafresh/backend/todo/controller/ToDoController.java
  src/main/java/com/leafresh/backend/todo/model/ToDoDTO.java
  src/main/java/com/leafresh/backend/todo/service/ToDoService.java
Labels: Developing

#75 feat: plant get by userNickname
  src/main/java/com/leafresh/backend/plant/controller/PlantController.java
  src/main/java/com/leafresh/backend/plant/model/PlantDTO.java
  src/main/java/com/leafresh/backend/plant/model/PlantEntity.java
  src/main/java/com/leafresh/backend/plant/repository/PlantRepository.java
  src/main/java/com/leafresh/backend/plant/service/PlantService.java
  src/main/resources/application.yml
Labels: Developing
